
## Lines of Code ##########################################################

locfiles=$(shell find . \( \( -name '*.agda' -o -name '*.in' \) ! -name '.*' \) )

loc :
	@wc $(locfiles)

debug_loc :
	@echo "locfiles=$(locfiles)"

# EOF
