#!/bin/bash

export prog=$1
shift
export output=$1
export actual=`$prog`

if [ "$actual" == "$output" ]; then
  true
else
  echo "Output \"$actual\" does not match expected output \"$output\""
  false
fi
