# HLint configuration file
# https://github.com/ndmitchell/hlint#readme

# Silence specific warnings
- ignore:
    name: "Use curry"
    within:
      - Agda.TypeChecking.Reduce.reduceWithBlocker
- ignore:
    name: "Use fmap"
    within:
      - Agda.TypeChecking.Rules.Application.checkPrimTrans
      - Agda.TypeChecking.Primitive.Cubical.primTrans'
      - Agda.TypeChecking.Primitive.Cubical.primComp
      - Agda.Syntax.Concrete.Operators.parsePat

# Warnings currently triggered by your code
- ignore: {name: "Avoid lambda"} # 116 hints
- ignore: {name: "Avoid lambda using `infix`"} # 12 hints
- ignore: {name: "Eta reduce"} # 374 hints
- ignore: {name: "Evaluate"} # 14 hints
- ignore: {name: "Fuse concatMap/map"} # 1 hint
- ignore: {name: "Fuse foldMap/fmap"} # 2 hints
- ignore: {name: "Fuse foldr/map"} # 8 hints
- ignore: {name: "Fuse mapM/map"} # 2 hints
- ignore: {name: "Hoist not"} # 18 hints
- ignore: {name: "Move brackets to avoid $"} # 47 hints
- ignore: {name: "Move guards forward"} # 2 hints
- ignore: {name: "Redundant $"} # 644 hints
- ignore: {name: "Redundant <$>"} # 46 hints
- ignore: {name: "Redundant =="} # 1 hint
- ignore: {name: "Redundant bracket"} # 2586 hints
- ignore: {name: "Redundant case"} # 1 hint
- ignore: {name: "Redundant flip"} # 2 hints
- ignore: {name: "Redundant guard"} # 6 hints
- ignore: {name: "Redundant id"} # 1 hint
- ignore: {name: "Redundant if"} # 4 hints
- ignore: {name: "Redundant irrefutable pattern"} # 36 hints
- ignore: {name: "Redundant lambda"} # 43 hints
- ignore: {name: "Redundant map"} # 2 hints
- ignore: {name: "Redundant multi-way if"} # 17 hints
- ignore: {name: "Redundant return"} # 2 hints
- ignore: {name: "Redundant section"} # 3 hints
- ignore: {name: "Replace case with fromMaybe"} # 3 hints
- ignore: {name: "Replace case with maybe"} # 2 hints
- ignore: {name: "Unused LANGUAGE pragma"} # 210 hints
- ignore: {name: "Use &&"} # 4 hints
- ignore: {name: "Use ++"} # 11 hints
- ignore: {name: "Use /="} # 1 hint
- ignore: {name: "Use :"} # 17 hints
- ignore: {name: "Use <$"} # 4 hints
- ignore: {name: "Use <$>"} # 18 hints
- ignore: {name: "Use <&>"} # 1 hint
- ignore: {name: "Use <=<"} # 3 hints
- ignore: {name: "Use >"} # 1 hint
- ignore: {name: "Use >=>"} # 1 hint
- ignore: {name: "Use Just"} # 1 hint
- ignore: {name: "Use LANGUAGE pragmas"} # 8 hints
- ignore: {name: "Use camelCase"} # 95 hints
- ignore: {name: "Use concatMap"} # 2 hints
- ignore: {name: "Use const"} # 75 hints
- ignore: {name: "Use elem"} # 2 hints
- ignore: {name: "Use empty"} # 1 hint
- ignore: {name: "Use fewer imports"} # 2 hints
- ignore: {name: "Use fmap"} # 5 hints
- ignore: {name: "Use fold"} # 1 hint
- ignore: {name: "Use fromMaybe"} # 1 hint
- ignore: {name: "Use id"} # 2 hints
- ignore: {name: "Use infix"} # 11 hints
- ignore: {name: "Use intercalate"} # 1 hint
- ignore: {name: "Use isNothing"} # 2 hints
- ignore: {name: "Use iterate"} # 1 hint
- ignore: {name: "Use join"} # 2 hints
- ignore: {name: "Use lambda-case"} # 55 hints
- ignore: {name: "Use list comprehension"} # 3 hints
- ignore: {name: "Use list literal"} # 12 hints
- ignore: {name: "Use list literal pattern"} # 2 hints
- ignore: {name: "Use map"} # 4 hints
- ignore: {name: "Use map once"} # 1 hint
- ignore: {name: "Use mapAndUnzipM"} # 1 hint
- ignore: {name: "Use mapMaybe"} # 3 hints
- ignore: {name: "Use maximum"} # 1 hint
- ignore: {name: "Use negate"} # 1 hint
- ignore: {name: "Use newtype instead of data"} # 29 hints
- ignore: {name: "Use notElem"} # 2 hints
- ignore: {name: "Use null"} # 4 hints
- ignore: {name: "Use record patterns"} # 38 hints
- ignore: {name: "Use second"} # 5 hints
- ignore: {name: "Use section"} # 19 hints
- ignore: {name: "Use sequenceA"} # 3 hints
- ignore: {name: "Use unless"} # 1 hint
- ignore: {name: "Use void"} # 13 hints
- ignore: {name: "Use zipWith"} # 2 hints
- ignore: {name: "Use ||"} # 4 hints

# Specify additional command line arguments
- arguments:
    - --ignore-glob=notes/papers/iird/paper.lhs
    - --ignore-glob=notes/style/haskell-style.lhs
    - --ignore-glob=notes/papers/implicit/examples.lhs
    - -XBangPatterns
    - -XBlockArguments
    - -XConstraintKinds
    - -XDefaultSignatures
    - -XDeriveFoldable
    - -XDeriveFunctor
    - -XDeriveGeneric
    - -XDeriveTraversable
    - -XDerivingStrategies
    - -XExistentialQuantification
    - -XFlexibleContexts
    - -XFlexibleInstances
    - -XFunctionalDependencies
    - -XGeneralizedNewtypeDeriving
    - -XInstanceSigs
    - -XLambdaCase
    - -XMultiParamTypeClasses
    - -XMultiWayIf
    - -XNamedFieldPuns
    - -XOverloadedStrings
    - -XPatternSynonyms
    - -XRankNTypes
    - -XRecordWildCards
    - -XScopedTypeVariables
    - -XStandaloneDeriving
    - -XTupleSections
    - -XTypeFamilies
    - -XTypeOperators
    - -XTypeSynonymInstances

# Add custom hints for this project
- hint:
    lhs: flip map
    rhs: for
    name: Replace flip map with for
    note: Prefer Agda.Utils.Functor.for over Data.Traversable.for
