resolver: lts-8.2

packages:
- '.'
- location:
    git: git@github.com:agda/agda.git
    commit: e89edb8f15b6fb5e6b9707b349526b7f11b874f8
  extra-dep: true
- location:
    git: "https://github.com/lwm/tasty-discover.git"
    commit: "HEAD"
  extra-dep: true

extra-deps:
  - tasty-th-0.1.4

flags: {}

extra-package-dbs: []
