name: Deploy

on:
  push:
    tags:
      - v[2-9]+.*

  workflow_run:
    workflows: ["Build, Test, and Benchmark"]
    branches: [master]
    types:
      - completed

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        # Andreas, 2022-10-18
        # We stick to '-latest' virtual environments here in the sense of
        # "most canonical", since this is the deploy action.
        # As of today (2024-02-05), the actual version information can be found in
        # https://github.com/actions/runner-images#available-images
        # Andreas, 2025-10-04
        # When you change the following values, also UPDATE the conditionals below.
        os:
          - windows-latest
          - macos-latest
          - macos-15-intel
          - ubuntu-latest
        ghc-ver: ['9.12.2']
        cabal-ver: [latest]

    env:
      ARGS: "--disable-executable-profiling --disable-library-profiling --flags=use-xdg-data-home"
      # Liang-Ting Chen (2021-01-01):
      # Cabal cannot compile statically with text-icu (required by the flag `enable-cluster-counting`),
      # see https://github.com/4e6/text-icu-static-example
      #
      # ASR (2022-06-01): The flag `--enable-split-sections` generates the warning
      # "-split-sections is not useful on this platform since it always uses subsections via symbols"
      # on MacOS (Issue #5940).
      LINUX_ARGS: "--flags=optimise-heavily --enable-executable-static  --enable-split-sections"
      MACOS_ARGS: "--flags=optimise-heavily"
      WIN64_ARGS: "--flags=optimise-heavily --enable-split-sections"
      MATRIX_OS: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:

    - name: Check out the master branch
      uses: actions/checkout@v6

    - name: Set up platform-dependent variables
      id: vars
      # We would like to disable SC2129 "Consider using { cmd1; cmd2; } >> file"
      # for the entire script but just placing it in the beginning does not work.
      # # shellcheck disable=SC2129
      run: |
        bindist="Agda"

        if [[ "$OSTYPE" == "msys"* ]]; then

          filename="win64.zip"
          exe="agda.exe"
          echo args="${ARGS} ${WIN64_ARGS}"                         >> "${GITHUB_OUTPUT}"
          echo content-type="application/zip"                       >> "${GITHUB_OUTPUT}"
          echo compress-cmd="cd ${bindist} && 7z a ${filename} -bb -mx=9 && mv ${filename} .." >> "${GITHUB_OUTPUT}"

        elif [[ "$MATRIX_OS" == "macos-15-intel" ]]; then

          filename="macOS-x64.tar.xz"
          exe="agda"
          echo args="${ARGS} ${MACOS_ARGS}"                         >> "${GITHUB_OUTPUT}"
          echo content-type="application/x-xz"                      >> "${GITHUB_OUTPUT}"
          echo compress-cmd="tar -a -cvf ${filename} -C ${bindist}" "${exe}"  >> "${GITHUB_OUTPUT}"

        elif [[ "$MATRIX_OS" == "macos-latest" ]]; then

          filename="macOS-arm64.tar.xz"
          exe="agda"
          echo args="${ARGS} ${MACOS_ARGS}"                         >> "${GITHUB_OUTPUT}"
          echo content-type="application/x-xz"                      >> "${GITHUB_OUTPUT}"
          echo compress-cmd="tar -a -cvf ${filename} -C ${bindist}" "${exe}"  >> "${GITHUB_OUTPUT}"

        elif [[ "$OSTYPE" == "linux-gnu"* ]]; then

          filename="linux.tar.xz"
          exe="agda"
          echo args="${ARGS} ${LINUX_ARGS}"                         >> "${GITHUB_OUTPUT}"
          echo content-type="application/x-xz"                      >> "${GITHUB_OUTPUT}"
          echo compress-cmd="tar -a -cvf ${filename} -C ${bindist}" "${exe}"  >> "${GITHUB_OUTPUT}"

        fi

        echo bindist="${bindist}"                                 >> "${GITHUB_OUTPUT}"
        echo exe="${exe}"                                         >> "${GITHUB_OUTPUT}"
        echo filename="${filename}"                               >> "${GITHUB_OUTPUT}"

    - name: Display build variables
      run: |
        echo "GITHUB_REF      = ${GITHUB_REF}"
        echo "GITHUB_REF_NAME = ${GITHUB_REF_NAME}"

        echo "args            = ${{ steps.vars.outputs.args         }}"
        echo "compress-cmd    = ${{ steps.vars.outputs.compress-cmd }}"
        echo "content-type    = ${{ steps.vars.outputs.content-type }}"
        echo "filename        = ${{ steps.vars.outputs.filename     }}"

    - name: Set up Alpine Linux with GHC
      uses: jirutka/setup-alpine@v1
      if:  ${{ runner.os == 'Linux' }}
      with:
        packages: >
          cabal
          g++
          gcc
          gmp-dev
          gmp-static
          musl-dev
          ncurses-dev
          ncurses-static
          zlib-static
          zlib-dev

    - uses: haskell-actions/setup@v2
      id: setup-haskell
      if:  ${{ runner.os != 'Linux' }}
      with:
        ghc-version: ${{ matrix.ghc-ver }}
        cabal-version: ${{ matrix.cabal-ver }}

    - name: Environment settings based on the Haskell setup
      if: ${{ runner.os != 'Linux' }}
      run: |
        GHC_VER=$(ghc --numeric-version)
        CABAL_VER=$(cabal --numeric-version)
        echo "GHC_VER   = ${GHC_VER}"
        echo "CABAL_VER = ${CABAL_VER}"
        echo "GHC_VER=${GHC_VER}"       >> "${GITHUB_ENV}"
        echo "CABAL_VER=${CABAL_VER}"   >> "${GITHUB_ENV}"
      # From now on, env.{GHC|CABAL}_VER are the precise versions.

    # See: https://github.com/haskell/text-icu/pull/86
    # pacman needs MSYS /usr/bin in PATH, but this breaks the latest cache action.
    # -  https://github.com/actions/cache/issues/1073
    # MSYS' pkg-config needs MSYS /mingw64/bin which we can safely add to the PATH

    - name: Install the required packages (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: |
        $env:PATH = "C:\msys64\usr\bin;$env:PATH"
        pacman -v --noconfirm -S mingw-w64-x86_64-pkgconf mingw-w64-x86_64-binutils
        echo "C:\msys64\mingw64\bin" | Out-File -FilePath "$env:GITHUB_PATH" -Append

      ## Old method:
      ##  Liang-Ting Chen (2025-06-03): To release Agda as a single executable,
      #   the flag `enable-cluster-counting` is disabled, so the library ICU is
      #   not needed as a dynamically linked library.
      #
      #   env:
      #   ICU_URL: 'https://github.com/unicode-org/icu/releases/download/release-69-1/icu4c-69_1-Win64-MSVC2019.zip'
      #   ICU_DIR: '/c/icu4c'
      #   ICU_FILE: 'icu4c.zip'
      # run: |
      #   curl -sSLo ${ICU_FILE} ${ICU_URL}
      #   7z e ${ICU_FILE} -o${ICU_DIR} && rm ${ICU_FILE}
      #   mkdir -p ${ICU_DIR}/include/unicode && mv ${ICU_DIR}/*.h ${ICU_DIR}/include/unicode

      #   cabal user-config update --augment="extra-lib-dirs: $(cygpath -w ${ICU_DIR})" --augment="extra-include-dirs: $(cygpath -w ${ICU_DIR}/include)"

#    - name: Install the ICU library (macOS)
#      if: ${{ runner.os == 'macOS' }}
#      run: |
#        brew install icu4c
#        ICU4C=$(brew --prefix)/opt/icu4c
#        # echo "${ICU4C}/bin" >> "${GITHUB_PATH}" ## Only needed for uconv
#        ICU_DIR=${ICU4C}/lib
#        echo "ICU_DIR=${ICU_DIR}"
#        echo "ICU_DIR=${ICU_DIR}" >> "${GITHUB_ENV}"
#        echo "PKG_CONFIG_PATH=${ICU_DIR}/pkgconfig" >> "${GITHUB_ENV}"

#    - name: Determine the ICU version
#      run: |
#        ICU_VER=$(pkg-config --modversion icu-i18n)
#        echo "ICU_VER=${ICU_VER}"
#        echo "ICU_VER=${ICU_VER}" >> "${GITHUB_ENV}"
#        ICU_MAJOR_VER=$(cut -d '.' -f 1 <<< "${ICU_VER}")
#        echo "ICU_MAJOR_VER=${ICU_MAJOR_VER}"
#        echo "ICU_MAJOR_VER=${ICU_MAJOR_VER}" >> "${GITHUB_ENV}"
#      # The output of unconv --version looks like "uconv v2.1  ICU 72.1" from which we extract "72.1"

    - name: Configure the build plan
      if: ${{ runner.os != 'Linux' }}
      run: |
        cabal configure ${{ steps.vars.outputs.args }}
        cabal build --dry-run
      # cabal build --dry-run creates dist-newstyle/cache/plan.json

    - name: Cache dependencies
      uses: actions/cache@v5
      if: ${{ runner.os != 'Linux' }}
      id: cache
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key:          deploy.yml-${{ runner.os }}-ghc-${{ env.GHC_VER }}-cabal-${{ env.CABAL_VER }}-${{ hashFiles('**/plan.json') }}
        restore-keys: deploy.yml-${{ runner.os }}-ghc-${{ env.GHC_VER }}-cabal-${{ env.CABAL_VER }}-

    - name: Build dependencies (on Alpine Linux)
      if: ${{ runner.os == 'Linux' }}
      shell: "alpine.sh {0}"
      run: |
        cabal update # Liang-Ting (2024-01-26): Alpine Linux has its own GHC toolchain
        cabal configure ${{ steps.vars.outputs.args }}
        cabal build exe:agda --only-dependencies

    - name: Build dependencies
      if: ${{ steps.cache.outputs.cache-hit != 'true' && runner.os != 'Linux' }}
      run: cabal build exe:agda --only-dependencies

    - name: Build Agda (on Alpine Linux)
      if: ${{ runner.os == 'Linux' }}
      shell: "alpine.sh {0}"
      run: cabal build exe:agda

    - name: Build Agda
      if: ${{ runner.os != 'Linux' }}
      run: cabal build exe:agda

    - name: Move artefacts to ${{ steps.vars.outputs.bindist }}
      run: |
        bindist="${{ steps.vars.outputs.bindist }}"
        mkdir -p "${bindist}"

        if [[ "$OSTYPE" == "msys"* ]]; then

          find dist-newstyle/build \( -name 'agda.exe' \) -type f -exec cp {} "${bindist}" \;
          strip "${bindist}"/*

        else

          find dist-newstyle/build \( -name 'agda' \) -type f -exec cp {} "${bindist}" \;
          strip "${bindist}"/*

        fi

        file "${{ steps.vars.outputs.bindist }}/agda"

    - name: Pack artefacts
      run: |
        ${{ steps.vars.outputs.compress-cmd }}

    - uses: actions/upload-artifact@v6
      with:
        path: ${{ steps.vars.outputs.filename }}
        name: ${{ steps.vars.outputs.filename }}
        if-no-files-found: error
        retention-days: 3

  sanity-check:
    if: ${{ !cancelled() }}
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, macos-15-intel, ubuntu-latest]
    env:
      MATRIX_OS: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up platform-dependent variables
      id: vars
      run: |
        if [[ "$OSTYPE" == "msys"* ]]; then

          osname="win64"
          ext="zip"
          decompress_cmd_base="7z x"

        elif [[ "$MATRIX_OS" == "macos-15-intel" ]]; then

          osname="macOS-x64"
          ext="tar.xz"
          decompress_cmd_base="tar -xf"

        elif [[ "$MATRIX_OS" == "macos-latest" ]]; then

          osname="macOS-arm64"
          ext="tar.xz"
          decompress_cmd_base="tar -xf"

        elif [[ "$OSTYPE" == "linux-gnu"* ]]; then

          osname="linux"
          ext="tar.xz"
          decompress_cmd_base="tar -xf"

        fi

        filename="${osname}.${ext}"
        echo filename="${filename}"                              >> "${GITHUB_OUTPUT}"
        echo decompress-cmd="${decompress_cmd_base} ${filename}" >> "${GITHUB_OUTPUT}"

    - name: Display variables
      run: |
        echo "filename        = ${{ steps.vars.outputs.filename       }}"
        echo "decompress-cmd  = ${{ steps.vars.outputs.decompress-cmd }}"

    - uses: actions/download-artifact@v7
      with:
        name: ${{ steps.vars.outputs.filename }}

    - name: Unpack artefacts
      run: |
        ${{ steps.vars.outputs.decompress-cmd }}

    - name: Run `agda --setup`
# Liang-Ting Chen (2025-06-21): Agda is currently not notarized on macOS, so
# the special attribute needs to be cleared before use.
      run: |
        if [[ "$MATRIX_OS" == "macos"* ]]; then
          xattr -c agda
        fi

        ./agda --setup

  deploy: # release a bindist if triggered on master or by a tag }}
    # Andreas, 2023-02-13: Also run this part when manually triggered ('workflow_dispatch')
    # if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'workflow_run' }}
    needs: sanity-check
    runs-on: ubuntu-latest
    # if: ${{ success() }}
    steps:

    - uses: actions/checkout@v6
      with:
        sparse-checkout: .

    - uses: actions/download-artifact@v7
      with:
        path: artifacts

    - name: Create/replace the nightly release and upload artifacts as release assets
      if: ${{ github.ref == 'refs/heads/master' }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        sha=$(git rev-parse --short=7 HEAD)

        git fetch -q origin 'refs/tags/*:refs/tags/*'
        last_tag=$(git tag -l | grep -e '^v[[:digit:]]\+\(\.[[:digit:]]\+\)\{2,\}$' | sort -Vr | head -n 1)
        echo "last_tag  = ${last_tag}"

        gh release delete 'nightly' --repo "${GITHUB_REPOSITORY}" --cleanup-tag --yes || true
        for i in artifacts/**/*; do mv "${i}" "$(dirname "${i}")/Agda-${sha}-$(basename "${i}")"; done
        ls -R artifacts
        gh release create 'nightly' artifacts/**/* --repo "${GITHUB_REPOSITORY}" --generate-notes --notes-start-tag "${last_tag}" --prerelease --title "${sha}@master"

    - name: Create a release with the bindist as release assets
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        echo "GITHUB_REF_NAME=${GITHUB_REF_NAME}"
        echo "GITHUB_REPOSITORY=${GITHUB_REPOSITORY}"

        gh release delete "${GITHUB_REF_NAME}" --repo "${GITHUB_REPOSITORY}" --yes || true
        gh release create "${GITHUB_REF_NAME}" -d --notes-file CHANGELOG.md --title "${GITHUB_REF_NAME}"
        for i in artifacts/**/*; do mv "${i}" "$(dirname "${i}")/Agda-${GITHUB_REF_NAME}-$(basename "${i}")"; done
        ls -R artifacts
        gh release upload "${GITHUB_REF_NAME}" artifacts/**/* --repo "${GITHUB_REPOSITORY}"
