name: Deploy

on:
  workflow_run:
    workflows: ["Build, Test, and Benchmark"]
    branches: [master]
    types:
      - completed
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  auto-cancel:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: Ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}

  build:
    if: ${{ always() }}
    needs: auto-cancel
    strategy:
      fail-fast: false
      matrix:
        # Andreas, 2022-10-18
        # We stick to '-latest' virtual environments here in the sense of
        # "most canonical", since this is the deploy action.
        # As of today, this is [windows-2022, macOS-11, ubuntu-20.04].
        os: [windows-latest, macos-latest]
        ghc-ver: ['9.6']
        # Use default (= latest) cabal version
        # cabal-ver: ['3.10']

        # Andreas, 2022-12-05, issue #6384:
        # Atm, building static executables with GHC 9.4 is broken on ubuntu-22.04,
        # so, we downgrade to ubuntu-20.04.
        # Andreas, 2023-03-16: GHC 9.6 does not seem to do static linking even on ubuntu-20.04.
        include:
          - os: ubuntu-20.04
            ghc-ver: '9.4'

    env:
      ARGS: "--disable-executable-profiling --disable-library-profiling"
      # Liang-Ting Chen (2021-01-01):
      # Cabal cannot compile statically with text-icu (required by the flag `enable-cluster-counting`),
      # see https://github.com/4e6/text-icu-static-example
      #
      # ASR (2022-06-01): The flag `--enable-split-sections` generates the warning
      # "-split-sections is not useful on this platform since it always uses subsections via symbols"
      # on MacOS (Issue #5940).
      LINUX_ARGS: "--enable-executable-static  --enable-split-sections"
      MACOS_ARGS: "--flags=enable-cluster-counting"
      WIN64_ARGS: "--flags=enable-cluster-counting  --enable-split-sections"
    outputs:
      sha: ${{ steps.vars.outputs.sha }}
    runs-on: ${{ matrix.os }}
    steps:

    - name: Check out the master branch
      uses: actions/checkout@v4

    - name: Set up platform-dependent variables
      id: vars
      run: |
        sha="$(git rev-parse --short=7 HEAD)"
        nightly=Agda-nightly

        echo sha="${sha}"                                           >> ${GITHUB_OUTPUT}
        echo nightly="${nightly}"                                   >> ${GITHUB_OUTPUT}

        if [[ "$OSTYPE" == "msys"* ]]; then

          filename="${nightly}-win64.zip"
          echo args="${ARGS} ${WIN64_ARGS}"                         >> ${GITHUB_OUTPUT}
          echo compress-cmd="7z a ${filename} ${nightly} -bb -mx=9" >> ${GITHUB_OUTPUT}
          echo content-type="application/zip"                       >> ${GITHUB_OUTPUT}
          echo exe="agda.exe"                                       >> ${GITHUB_OUTPUT}
          echo filename="${filename}"                               >> ${GITHUB_OUTPUT}

        elif [[ "$OSTYPE" == "darwin"* ]]; then

          filename="${nightly}-macOS.tar.xz"
          echo args="${ARGS} ${MACOS_ARGS}"                         >> ${GITHUB_OUTPUT}
          echo compress-cmd="tar -a -cvf ${filename} ${nightly}"    >> ${GITHUB_OUTPUT}
          echo content-type="application/x-xz"                      >> ${GITHUB_OUTPUT}
          echo exe="agda"                                           >> ${GITHUB_OUTPUT}
          echo filename="${filename}"                               >> ${GITHUB_OUTPUT}

        elif [[ "$OSTYPE" == "linux-gnu"* ]]; then

          filename="${nightly}-linux.tar.xz"
          echo args="${ARGS} ${LINUX_ARGS}"                         >> ${GITHUB_OUTPUT}
          echo compress-cmd="tar -a -cvf ${filename} ${nightly}"    >> ${GITHUB_OUTPUT}
          echo content-type="application/x-xz"                      >> ${GITHUB_OUTPUT}
          echo exe="agda"                                           >> ${GITHUB_OUTPUT}
          echo filename="${filename}"                               >> ${GITHUB_OUTPUT}

        fi

    - name: Display build variables
      run: |
        echo args         = ${{ steps.vars.outputs.args         }}
        echo compress-cmd = ${{ steps.vars.outputs.compress-cmd }}
        echo content-type = ${{ steps.vars.outputs.content-type }}
        echo filename     = ${{ steps.vars.outputs.filename     }}
        echo nightly      = ${{ steps.vars.outputs.nightly      }}

    - uses: haskell-actions/setup@v2
      id: setup-haskell
      with:
        ghc-version: ${{ matrix.ghc-ver }}
        cabal-version: latest
        # cabal-version: ${{ matrix.cabal-ver }}

    - name: Environment settings based on the Haskell setup
      run: |
        GHC_VER=$(ghc --numeric-version)
        CABAL_VER=$(cabal --numeric-version)
        echo "GHC_VER   = ${GHC_VER}"
        echo "CABAL_VER = ${CABAL_VER}"
        echo "GHC_VER=${GHC_VER}"       >> "${GITHUB_ENV}"
        echo "CABAL_VER=${CABAL_VER}"   >> "${GITHUB_ENV}"
      # From now on, env.{GHC|CABAL}_VER are the precise versions.

    # See: https://github.com/haskell/text-icu/pull/86
    # pacman needs MSYS /usr/bin in PATH, but this breaks the latest cache action.
    # -  https://github.com/actions/cache/issues/1073
    # MSYS' pkg-config needs MSYS /mingw64/bin which we can safely add to the PATH
    #
    - name: Install the ICU library (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: |
        $env:PATH = "C:\msys64\usr\bin;$env:PATH"
        pacman -v --noconfirm -Sy mingw-w64-x86_64-pkg-config mingw-w64-x86_64-icu
        echo "C:\msys64\mingw64\bin" | Out-File -FilePath "$env:GITHUB_PATH" -Append

      ## Old method:
      # env:
      #   ICU_URL: 'https://github.com/unicode-org/icu/releases/download/release-69-1/icu4c-69_1-Win64-MSVC2019.zip'
      #   ICU_DIR: '/c/icu4c'
      #   ICU_FILE: 'icu4c.zip'
      # run: |
      #   curl -sSLo ${ICU_FILE} ${ICU_URL}
      #   7z e ${ICU_FILE} -o${ICU_DIR} && rm ${ICU_FILE}
      #   mkdir -p ${ICU_DIR}/include/unicode && mv ${ICU_DIR}/*.h ${ICU_DIR}/include/unicode

      #   cabal user-config update --augment="extra-lib-dirs: $(cygpath -w ${ICU_DIR})" --augment="extra-include-dirs: $(cygpath -w ${ICU_DIR}/include)"

    - name: Set up for the ICU library (macOS)
      if: ${{ runner.os == 'macOS' }}
      run: |
        ICU4C=$(brew --prefix)/opt/icu4c
        # echo "${ICU4C}/bin" >> "${GITHUB_PATH}" ## Only needed for uconv
        ICU_DIR=${ICU4C}/lib
        echo "ICU_DIR=${ICU_DIR}"
        echo "ICU_DIR=${ICU_DIR}" >> "${GITHUB_ENV}"
        echo "PKG_CONFIG_PATH=${ICU_DIR}/pkgconfig" >> "${GITHUB_ENV}"

    - name: Determine the ICU version
      run: |
        ICU_VER=$(pkg-config --modversion icu-i18n)
        echo "ICU_VER=${ICU_VER}"
        echo "ICU_VER=${ICU_VER}" >> "${GITHUB_ENV}"
        ICU_MAJOR_VER=$(cut -d '.' -f 1 <<< "${ICU_VER}")
        echo "ICU_MAJOR_VER=${ICU_MAJOR_VER}"
        echo "ICU_MAJOR_VER=${ICU_MAJOR_VER}" >> "${GITHUB_ENV}"
      # The output of unconv --version looks like "uconv v2.1  ICU 72.1" from which we extract "72.1"

    - name: Configure the build plan
      run: |
        cabal configure ${{ steps.vars.outputs.args }}
        cabal build --dry-run
      # cabal build --dry-run creates dist-newstyle/cache/plan.json
      # Keep a watch on this `cabal-3.9 build --dry-run` bug:
      # https://github.com/haskell/cabal/issues/8706

    - name: Cache dependencies
      uses: actions/cache@v3
      id: cache
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key:          deploy.yml-${{ runner.os }}-ghc-${{ env.GHC_VER }}-cabal-${{ env.CABAL_VER }}-${{ hashFiles('**/plan.json') }}
        restore-keys: deploy.yml-${{ runner.os }}-ghc-${{ env.GHC_VER }}-cabal-${{ env.CABAL_VER }}-

    - name: Build dependencies
      if: ${{ !steps.cache.outputs.cache-hit }}
      run: cabal build exe:agda exe:agda-mode --only-dependencies

    - name: Build Agda
      run: cabal build exe:agda exe:agda-mode

    # - name: Build Agda
    #   uses: nick-invision/retry@v2
    #   # Liang-Ting (2020-12-8):
    #   # Due to a ghc bug on Windows, it is necessary to build Agda twice (or more)
    #   # See:
    #   #   - https://github.com/agda/agda/issues/4543
    #   #   - https://gitlab.haskell.org/ghc/ghc/-/issues/18634
    #   with:
    #     max_attempts: 3
    #     timeout_minutes: 60
    #     retry_on: error
    #     command: cabal build exe:agda exe:agda-mode

    - name: Move artefacts to ${{ steps.vars.outputs.nightly }}
      env:
        DLL: "/c/msys64/mingw64/bin/libicu*.dll"
          ## was /c/icu4c/icu*.dll
      run: |
        nightly="${{ steps.vars.outputs.nightly }}"
        mkdir -p "${nightly}"/bin
        cp -a src/data "${nightly}"

        if [[ "$OSTYPE" == "msys"* ]]; then

          find dist-newstyle/build \( -name 'agda.exe' -o -name 'agda-mode.exe' \) -type f -exec cp {} "${nightly}"/bin \;
          cp -a .github/*.bat "${nightly}"
          cp ${DLL} "${nightly}"/bin/
          C:/ProgramData/Chocolatey/bin/strip.exe "${nightly}"/bin/*

        else

          find dist-newstyle/build \( -name 'agda' -o -name 'agda-mode' \) -type f -exec cp {} "${nightly}"/bin \;
          strip "${nightly}"/bin/*
          cp -a .github/*.sh "${nightly}"

          if [[ "$OSTYPE" == "darwin"* ]]; then

          # Change the path to the dynamic library icu4c to the run-time search path:
          #
          # 1. the same directory of executable, i.e. @executable_path
          # 2. @executable_path/../lib
          # 3. the default location of system-wide icu4c installed by homebrew, ie. /usr/local/opt/icu4c/lib
          #
          mkdir "${nightly}"/lib
          cp ${ICU_DIR}/libicuuc.${ICU_MAJOR_VER}.dylib ${ICU_DIR}/libicui18n.${ICU_MAJOR_VER}.dylib ${ICU_DIR}/libicudata.${ICU_MAJOR_VER}.dylib "${nightly}"/lib
          install_name_tool -change ${ICU_DIR}/libicuuc.${ICU_MAJOR_VER}.dylib @rpath/libicuuc.${ICU_MAJOR_VER}.dylib "${nightly}"/bin/agda
          install_name_tool -change ${ICU_DIR}/libicui18n.${ICU_MAJOR_VER}.dylib @rpath/libicui18n.${ICU_MAJOR_VER}.dylib "${nightly}"/bin/agda
          install_name_tool -add_rpath @executable_path -add_rpath @executable_path/../lib -add_rpath ${ICU_DIR} "${nightly}"/bin/agda
          otool -L "${nightly}"/bin/agda

          fi
        fi

        file ${{ steps.vars.outputs.nightly }}/bin/agda

    - name: Compress the Agda executable
      # UPX does not support macOS Big Sur.
      # Liang-Ting Chen (2020-01-04):
      #   Executables compressed by UPX are not usable on macOS 11 (Big Sur),
      #   see https://github.com/upx/upx/issues/424
      if: ${{ runner.os != 'macOS' }}
      uses: svenstaro/upx-action@v2
      with:
        file: ${{ steps.vars.outputs.nightly }}/bin/${{ steps.vars.outputs.exe }}
        strip: false

    - name: Display the version information
      run: |
        ${{ steps.vars.outputs.nightly }}/bin/agda --version

    - name: Pack artefacts
      run: |
        ${{ steps.vars.outputs.compress-cmd }}

    - uses: actions/upload-artifact@v3
      with:
        path: ${{ steps.vars.outputs.filename }}
        name: ${{ steps.vars.outputs.filename }}
        if-no-files-found: error
        retention-days: 3

  deploy: # release a nightly build if triggered on master }}
    if: ${{ github.ref == 'refs/heads/master' }}
    # Andreas, 2023-02-13: Also run this part when manually triggered ('workflow_dispatch')
    # if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'workflow_run' }}
    needs: build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Create/replace the nightly release and upload artifacts as release assets
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh release delete 'nightly' --repo agda/agda --cleanup-tag --yes || true
        ls -R artifacts
        gh release create 'nightly' artifacts/**/* --repo agda/agda --generate-notes --notes-start-tag v2.6.3 --title "Nightly Build (${{ needs.build.outputs.sha }}@master)"
