name: Lint

on:
  push:
    branches:
      - master
      - ci-*
      - release*
    paths: &trigger_path_list
      - '.github/workflows/lint.yaml'
      - '.hlint.yaml'
      - 'Agda.cabal'
      - 'src/**'
      - 'test/**'

  pull_request:
    # See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
    types:
      - opened
      - reopened
      - synchronize
    paths: *trigger_path_list

jobs:
  hlint:
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
      && !contains(github.event.head_commit.message, '[ci skip]')
      && !contains(github.event.head_commit.message, '[github skip]')
      && !contains(github.event.head_commit.message, '[skip github]')

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # We don't currently have any submodules that need hlinting,
    # so we don't checkout submodules recursively here.

    - name: Set up hlint
      uses: rwe/actions-hlint-setup@v1
      with:
        version: '3.5'

    - name: Run hlint
      uses: rwe/actions-hlint-run@v2
      with:
        path: '["src/", "test/"]'
