name: User Manual

on:
  push:
    branches:
    - master
    - ci-*
    - release*
    paths: &trigger_path_list
    - 'doc/user-manual/**'
    - '.github/workflows/user_manual.yml'
  pull_request:
    paths: *trigger_path_list

jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
      && !contains(github.event.head_commit.message, '[ci skip]')
      && !contains(github.event.head_commit.message, '[github skip]')
      && !contains(github.event.head_commit.message, '[skip github]')

    runs-on: ubuntu-24.04
    env:
      python-version: '3.13'
    steps:

    - uses: actions/checkout@v5

    - name: Install imagemagick (convert)
      run: |
        sudo apt-get update
        sudo apt-get install imagemagick

    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ env.python-version }}

    - name: Install dependencies
      run: |
        make -C doc/user-manual requirements

    # Source: https://medium.com/@balazskocsis/latex-in-github-actions-3cf2d591fee8
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt install texlive-full -y
      # Install the full version
      # or only your required latex packages
      # sudo apt install -y \
      #     texlive-base \
      #     texlive-latex-base \
      #     texlive-latex-recommended \
      #     texlive-latex-extra \
      #     texlive-fonts-recommended \
      #     latexmk \
      #     lmodern

    # # This action vanished from github without warning
    # - name: Setup TeX Live
    #   uses: teatimeguest/setup-texlive-action@v3
    #   with:
    #     packages: >-
    #       scheme-basic
    #       anyfontsize
    #       bbm
    #       bbm-macros
    #       booktabs
    #       capt-of
    #       cmap
    #       colortbl
    #       dvipng
    #       ellipse
    #       etoolbox
    #       fancyvrb
    #       float
    #       fncychap
    #       fontawesome5
    #       framed
    #       keystroke
    #       latexmk
    #       mathtools
    #       needspace
    #       parskip
    #       pict2e
    #       psnfss
    #       stmaryrd
    #       tabulary
    #       tex-gyre
    #       titlesec
    #       upquote
    #       varwidth
    #       wrapfig
    #       xcolor
    #       zapfchan

    - name: Build User Manual in PDF
      run: |
        export PATH=$HOME/texlive/bin/x86_64-linux:$PATH
        make user-manual-pdf

    - name: Build User Manual in HTML
      # Note: latex is already needed to build HTML (for math formulas).
      run: |
        export PATH=$HOME/texlive/bin/x86_64-linux:$PATH
        make user-manual-html

    - uses: actions/upload-artifact@v4
      with:
        name: user-manual-pdf
        path: doc/user-manual.pdf
