name: User Manual

on:
  push:
    branches:
    - master
    - ci-*
    - release*
    paths: &trigger_path_list
    - 'doc/user-manual/**'
    - '.github/workflows/user_manual.yml'
  pull_request:
    paths: *trigger_path_list

jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, '[skip ci]')
      && !contains(github.event.head_commit.message, '[ci skip]')
      && !contains(github.event.head_commit.message, '[github skip]')
      && !contains(github.event.head_commit.message, '[skip github]')

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -r doc/user-manual/requirements.txt
    - name: Install Tex Live and LaTeX packages
      run: |
        export PATH=$HOME/texlive/bin/x86_64-linux:$PATH
        curl -Lo /tmp/texlive.tar.gz https://github.com/jimhester/ubuntu-bin/releases/download/latest/texlive.tar.gz
        tar xzf /tmp/texlive.tar.gz -C ~
        tlmgr option repository http://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2017/tlnet-final
        tlmgr update --self
        tlmgr install anyfontsize bbm capt-of cmap dvipng fncychap keystroke latexmk needspace tex-gyre
    - name: Build User Manual in HTML
      run: |
        export PATH=$HOME/texlive/bin/x86_64-linux:$PATH
        make user-manual-html
    - name: Build User Manual in PDF
      run: |
        export PATH=$HOME/texlive/bin/x86_64-linux:$PATH
        make user-manual-pdf
    - uses: actions/upload-artifact@v2
      with:
        name: user-manual-pdf
        path: doc/user-manual.pdf
