name: Whitespace
on:
  push:
    branches:
    - master
    - ci-*
    - release*
  pull_request:

jobs:
  check:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout agda sources
      uses: actions/checkout@v4

    - name: Check for whitespace violations
      uses: andreasabel/fix-whitespace-action@v1

    - name: Check encoding of Parser.y
      run: |
        make check-encoding

    - name: Check for LANGUAGE RecursiveDo
      run: |
        make check-mdo

    - name: Check building the source tarball
      run: |
        cabal sdist
