#!/bin/bash

source .travis/header.sh
set -e

fold_timer_cmd "check.whitespace" make check-whitespace

title "Suite of successful tests"
fold_timer_cmd "successful.tests" \
  make AGDA_TESTS_OPTIONS="-j${PARALLEL_TESTS} --hide-successes" TASTY_ANSI_TRICKS=false BUILD_DIR=$BUILD_DIR succeed

title "Suite of failing tests"
fold_timer_cmd "failing.tests" \
  make AGDA_TESTS_OPTIONS="-j${PARALLEL_TESTS} --hide-successes" TASTY_ANSI_TRICKS=false BUILD_DIR=$BUILD_DIR fail

title "Suite of interaction tests"
fold_timer_cmd "interaction.tests" \
  make BUILD_DIR=$BUILD_DIR interaction

title "Suite of interactive tests"
fold_timer_cmd "interactive.tests" \
  make BUILD_DIR=$BUILD_DIR interactive
# We don't run LaTeX/XeLaTeX/LuaLaTeX on Travis (see Issues #1022 and
# #1675), but we still compare the generated tex/html files with the
# golden files.

title "Suite of tests for the LaTeX and HTML backends"
fold_timer_cmd "latex_html.tests" \
  make AGDA_TESTS_OPTIONS="-j${PARALLEL_TESTS} --hide-successes" \
    TASTY_ANSI_TRICKS=false \
    BUILD_DIR=$BUILD_DIR DONT_RUN_LATEX="Y" \
    latex-html-test
   
title "Suite of examples"
fold_timer_cmd "examples" \
  make BUILD_DIR=$BUILD_DIR examples

title "Standard library" 
fold_timer_cmd "library.tests" \
  make BUILD_DIR=$BUILD_DIR library-test

title "Successfull tests using Agda as a Haskell library"
fold_timer_cmd "api.tests" \
make BUILD_DIR=$BUILD_DIR api-test

title "User manual"
fold_timer_cmd "user.manual.tests" \
  make AGDA_TESTS_OPTIONS="-j${PARALLEL_TESTS} --hide-successes" \
    TASTY_ANSI_TRICKS=false \
    BUILD_DIR=$BUILD_DIR \
    user-manual-test

title "Internal test suite"
fold_timer_cmd "internal.tests" \
  make AGDA_TESTS_OPTIONS="-j${PARALLEL_TESTS} --hide-successes"\
  TASTY_ANSI_TRICKS=false \
  BUILD_DIR=$BUILD_DIR \
  internal-tests

title "Benchmark suite without creating logs"
fold_timer_cmd "benchmark" \
  make BUILD_DIR=$BUILD_DIR benchmark-without-logs

##################################################################################
# Andreas, 2019-08-20: disable compiler test on ghc 8.0 since it takes too long,
# making the whole travis run fail.
# Ulf, 2019-08-29: only disable the stdlib compiler test

title "Compiler tests"
travis_fold start "compiler.tests"
travis_timer_start 

make AGDA_TESTS_OPTIONS="-j${PARALLEL_TESTS} --hide-successes" TASTY_ANSI_TRICKS=false BUILD_DIR=$BUILD_DIR compiler-test
if [[ $GHC_VER != "8.0.2" ]]; then
  subtitle "Standard Library Compiler tests"
  make AGDA_TESTS_OPTIONS="-j${PARALLEL_TESTS} --hide-successes" TASTY_ANSI_TRICKS=false BUILD_DIR=$BUILD_DIR stdlib-compiler-test;
fi

travis_timer_finish
travis_fold end "compiler.test"

title "Successfull tests using Agda as a Haskell library"
fold_timer_cmd "lib.successful.tests" \
  make AGDA_TESTS_OPTIONS="-j${PARALLEL_TESTS} --hide-successes" TASTY_ANSI_TRICKS=false BUILD_DIR=$BUILD_DIR lib-succeed

title "Interaction tests using the standard library"
fold_timer_cmd "library.interaction.tests" \
  make BUILD_DIR=$BUILD_DIR lib-interaction

title "TAGS"
fold_timer_cmd "tag.tests" \
  make BUILD_DIR=$BUILD_DIR TAGS

title "Testing the size-solver program"
travis_fold start "test.size.solver"
travis_timer_start 

stack install shelltestrunner
make test-size-solver

travis_fold end "test.size.solver"
travis_timer_finish 

title "Testing the Emacs mode"
fold_timer_cmd "emacs.mode.tests" \
  make BUILD_DIR=$BUILD_DIR testing-emacs-mode

title "Installing the agda-bisect program"
fold_timer_cmd "build.agda.bisect" \
  make install-agda-bisect
