#!/bin/bash

source .travis/header.sh
set -e

fold_timer_cmd "check.whitespace" make check-whitespace

fold_timer_cmd "successful.tests" \
  make AGDA_TESTS_OPTIONS="-j${PARALLEL_TESTS} --hide-successes" TASTY_ANSI_TRICKS=false BUILD_DIR=$BUILD_DIR succeed

fold_timer_cmd "failing.tests" \
  make AGDA_TESTS_OPTIONS="-j${PARALLEL_TESTS} --hide-successes" TASTY_ANSI_TRICKS=false BUILD_DIR=$BUILD_DIR fail

fold_timer_cmd "interaction.tests" \
  make BUILD_DIR=$BUILD_DIR interaction

fold_timer_cmd "interactive.tests" \
  make BUILD_DIR=$BUILD_DIR interactive
# We don't run LaTeX/XeLaTeX/LuaLaTeX on Travis (see Issues #1022 and
# #1675), but we still compare the generated tex/html files with the
# golden files.

fold_timer_cmd "latex_html.tests" \
  make AGDA_TESTS_OPTIONS="-j${PARALLEL_TESTS} --hide-successes" \
    TASTY_ANSI_TRICKS=false \
    BUILD_DIR=$BUILD_DIR DONT_RUN_LATEX="Y" \
    latex-html-test

fold_timer_cmd "examples" \
  make BUILD_DIR=$BUILD_DIR examples

fold_timer_cmd "library.tests" \
  make BUILD_DIR=$BUILD_DIR library-test

fold_timer_cmd "library.tests" \
make BUILD_DIR=$BUILD_DIR api-test

fold_timer_cmd "user.manual.tests" \
  make AGDA_TESTS_OPTIONS="-j${PARALLEL_TESTS} --hide-successes" \
    TASTY_ANSI_TRICKS=false \
    BUILD_DIR=$BUILD_DIR \
    user-manual-test

fold_timer_cmd "library.tests" \
  make AGDA_TESTS_OPTIONS="-j${PARALLEL_TESTS} --hide-successes"\
  TASTY_ANSI_TRICKS=false \
  BUILD_DIR=$BUILD_DIR \
  internal-tests

fold_timer_cmd "benchmark" \
  make BUILD_DIR=$BUILD_DIR benchmark-without-logs

##################################################################################
# Andreas, 2019-08-20: disable compiler test on ghc 8.0 since it takes too long,
# making the whole travis run fail.
# Ulf, 2019-08-29: only disable the stdlib compiler test

travis_fold start "compiler.tests"
travis_timer_start 

make AGDA_TESTS_OPTIONS="-j${PARALLEL_TESTS} --hide-successes" TASTY_ANSI_TRICKS=false BUILD_DIR=$BUILD_DIR compiler-test
if [[ $GHC_VER != "8.0.2" ]]; then
  make AGDA_TESTS_OPTIONS="-j${PARALLEL_TESTS} --hide-successes" TASTY_ANSI_TRICKS=false BUILD_DIR=$BUILD_DIR stdlib-compiler-test;
fi

travis_timer_finish
travis_fold end "compiler.test"

fold_timer_cmd "lib.successful.tests" \
  make AGDA_TESTS_OPTIONS="-j${PARALLEL_TESTS} --hide-successes" TASTY_ANSI_TRICKS=false BUILD_DIR=$BUILD_DIR lib-succeed

fold_timer_cmd "library.interaction.tests" \
  make BUILD_DIR=$BUILD_DIR lib-interaction

fold_timer_cmd "tag.tests" \
  make BUILD_DIR=$BUILD_DIR TAGS

travis_fold start "test.size.solver"
travis_timer_start 

cabal v1-install --allow-newer=ansi-terminal -v0 --ghc-option=-w --force-reinstalls shelltestrunner
make test-size-solver

travis_fold end "test.size.solver"
travis_timer_finish 

fold_timer_cmd "emacs.mode.tests" \
  make BUILD_DIR=$BUILD_DIR testing-emacs-mode

fold_timer_cmd "build.agda.bisect" \
  make install-agda-bisect
