#!/bin/bash
source .travis/header.sh
set -e

##############################################################################
# Build environment information

travis_fold start "env.info"

echo "*** GHC version ***"
ghc --version
echo "*** Cabal version ***"
cabal --version
echo "*** Haddock version ***"
haddock --version
echo "*** Emacs version ***"
emacs --version

# The container environment reports a wrong number of cores. We use
# a `sed` script (from https://github.com/hvr/multi-ghc-travis) for
# commenting out `jobs: $ncpus` in the Cabal configuration file.
travis_retry cabal update
sed -i 's/^jobs:/-- jobs:/' $HOME/.cabal/config
cat $HOME/.cabal/config
travis_retry cabal update
travis_retry cabal fetch alex happy

cabal install -v0 alex happy
echo "*** Alex version ***"
alex --version
echo "*** Happy version ***"
happy --version

travis_fold end "env.info"

##############################################################################
# Installing the dependencies

# N.B. `cabal install` doesn't set up the number of jobs by default
# (cabal-install 1.22.4.0). See https://github.com/haskell/cabal/issues/2628.

# N.B. We use the `--force-reinstalls` option [Issue 1520].

# We are using `make CABAL_OPTS...` because we are including the
# options to `cabal install` set up in the `Makefile`.

travis_fold start "build.dependencies"

travis_retry cabal fetch \
  `cabal install --dependencies-only --enable-tests --force-reinstalls --dry-run | sed 1,2d | sed "s|(latest[^)]*)||g"`
make CABAL_OPTS='-v0 --only-dependencies --force-reinstalls' install-bin

travis_fold end "build.dependencies"
##############################################################################
# Installing Agda

travis_fold start "build.agda"

make BUILD_DIR=$BUILD_DIR CABAL_OPTS=-v1 install-bin

travis_fold end "build.agda"

##############################################################################
# Getting the standard library

travis_fold start "fetch.std-lib"

make up-to-date-std-lib

travis_fold end "fetch.std-lib"

###############################################################################
## Installing a recent version of Node (see Issue #2192)
#
#cd $HOME
#travis_retry wget https://nodejs.org/download/release/${NODE_VERSION}/${NODE_TARBALL}
#tar xJf ${NODE_TARBALL}
#cd $AGDA_HOME
#echo "*** Node version ***"
#node --version
