#!/bin/bash
 
source .travis/header.sh
set -ev

# Show build environment
vmInfo
ghcInfo
echo "*** Cabal version ***"
cabal --version
# The container environment reports a wrong number of cores. We use
# a `sed` script (from https://github.com/hvr/multi-ghc-travis) for
# commenting out `jobs: $ncpus` in the Cabal configuration file.
travis_retry cabal update &&
sed -i 's/^jobs:/-- jobs:/' $HOME/.cabal/config &&
cat $HOME/.cabal/config &&
travis_retry cabal update &&
travis_retry cabal fetch alex happy &&
cabal install -v0 alex happy &&
echo "*** Alex version ***" &&
alex --version &&
echo "*** Happy version ***" &&
happy --version

##############################################################################
# Installing the dependencies

# N.B. that `cabal install` doesn't set up the number of jobs by default
# (cabal-install 1.22.4.0). See https://github.com/haskell/cabal/issues/2628.

# TODO (2016-02-21): Split the long lines (`\` doesn't work).

# N.B. that we use the `--force-reinstalls` option [Issue 1520].

# We are using `make CABAL_OPTS...` because we are including the
# options to `cabal install` set up in the `Makefile`.
travis_retry cabal fetch `cabal install --dependencies-only --enable-tests --force-reinstalls --dry-run | sed 1,2d | sed "s|(latest[^)]*)||g"` &&
make CABAL_OPTS='-v0 --only-dependencies --force-reinstalls' install-bin

##############################################################################
# Installing Agda


make BUILD_DIR=$BUILD_DIR CABAL_OPTS=-v1 install-bin

##############################################################################
# Getting the standard library

make up-to-date-std-lib

travis_retry curl -Lo /tmp/texlive.tar.gz https://github.com/jimhester/ubuntu-bin/releases/download/latest/texlive.tar.gz &&
tar xzf /tmp/texlive.tar.gz -C ~ &&
tlmgr update --self &&
tlmgr install anyfontsize bbm capt-of cmap dvipng fncychap keystroke latexmk needspace &&
echo "*** pdfLaTeX version ***" &&
pdflatex --version &&
echo "*** Latexmk version ***" &&
latexmk --version

##############################################################################
# Installing a recent version of Node (see Issue #2192)

cd $HOME &&
travis_retry wget https://nodejs.org/download/release/${NODE_VERSION}/${NODE_TARBALL} &&
tar xJf ${NODE_TARBALL} &&
cd $AGDA_HOME &&
echo "*** Node version ***" &&
node --version
