#!/bin/bash
source .travis/header.sh
set -ev

vmInfo
ghcInfo
echo "*** Cabal version ***"
cabal --version
echo "*** GHC version ***"
ghc --version
echo "*** Haddock version ***"
haddock --version
echo "*** Emacs version ***"
emacs --version
travis_retry cabal update
sed -i 's/^jobs:/-- jobs:/' $HOME/.cabal/config
cat $HOME/.cabal/config
travis_retry cabal update
travis_retry cabal fetch alex happy
cabal install -v0 alex happy
echo "*** Alex version ***"
alex --version
echo "*** Happy version ***"
happy --version

travis_retry cabal fetch `cabal v1-install --dependencies-only --enable-tests --force-reinstalls --dry-run | sed 1,2d | sed "s|(latest[^)]*)||g"` &&
make CABAL_OPTS='-v0 --only-dependencies --force-reinstalls' install-bin
