#!/bin/bash
source .travis/header.sh
set -e

travis_fold start "env.info"

echo "*** GHC version ***"
ghc --version
echo "*** Cabal version ***"
cabal --version
echo "*** Haddock version ***"
haddock --version
echo "*** Emacs version ***"
emacs --version

travis_fold end "env.info"

##############################################################################
# Installing the dependencies

# N.B. `cabal install` doesn't set up the number of jobs by default
# (cabal-install 1.22.4.0). See https://github.com/haskell/cabal/issues/2628.

# N.B. We use the `--force-reinstalls` option [Issue 1520].

# We are using `make CABAL_OPTS...` because we are including the
# options to `cabal install` set up in the `Makefile`.

travis_fold start "build.dependencies"

travis_retry cabal update
sed -i 's/^jobs:/-- jobs:/' $HOME/.cabal/config
cat $HOME/.cabal/config
travis_retry cabal update
travis_retry cabal fetch alex happy
cabal install -v0 alex happy
echo "*** Alex version ***"
alex --version
echo "*** Happy version ***"
happy --version

travis_retry cabal fetch \
  `cabal v1-install --dependencies-only --enable-tests --force-reinstalls --dry-run | sed 1,2d | sed "s|(latest[^)]*)||g"`
make CABAL_OPTS='-v0 --only-dependencies --force-reinstalls' install-bin

travis_fold end "build.dependencies"
