#!/bin/bash

source .travis/header.sh
set -e

# We test on Stackage the non-default Agda flags.
#
# Default flags: `cpp` instead of `cpphs`, `debug` off and
# `enable-cluster-counting` off.
#
# Issues related to the flags: `cpp` instead of `cpphs` [Issue #1647]
# and the `debug` flag [Issue #2070].

##############################################################################
# Show build environment

travis_fold start "build.env"

echo "*** GHC version ***"
ghc --version 
echo "*** Stack version ***" 
stack --version
echo "*** Haddock version ***"
haddock --version
echo "*** Emacs version ***"
emacs --version

travis_fold end "build.env"

##############################################################################
# Installing the dependencies

fold_cmd "build.dependencies" stack build $ARGS --no-terminal --only-dependencies ${AGDA_STACK_BUILD_FLAGS} --ghc-options=-O0

##############################################################################
# Some tests

# ASR (2016-09-17). Running the following tests, which use stack, here
# instead of in the `script` section is faster because Agda's
# dependencies are not installed again.

##############################################################################

fold_cmd "build.agda" travis_wait 35 stack build $ARGS --no-terminal ${AGDA_STACK_BUILD_FLAGS} --ghc-options=-O0
