{-# OPTIONS -fglasgow-exts #-}

-- Generated by Alonzo

module Proj where
import RTS
import qualified RTP
import qualified RTN
import qualified AlonzoPrelude
import qualified RTP
name1 = "showTrue"
d1 = d1_1
  where d1_1 _ = cast ("tt")
name2 = "T4"
 
data T2 a b c d = C3 a b c d
d2 = ()
name3 = "C"
name4 = "g"
d4 = d4_1
  where d4_1 _ v0 = cast AlonzoPrelude.d6
name7 = "f14"
d7 = d7_1
  where d7_1 (Proj.C3 v0 _ v1 v2)
          = cast (\ w -> Proj.d4 (cast v0) (cast v2))
name13 = "mainS"
d13 = d13_1
  where d13_1
          = cast
              (AlonzoPrelude.d22 (cast AlonzoPrelude.d5) (cast RTP._String)
                 (cast Proj.d1)
                 (cast
                    (AlonzoPrelude.d16 (cast Proj.d2) (cast ()) (cast ())
                       (cast (AlonzoPrelude.d11 (cast ())))
                       (cast Proj.d7)
                       (cast
                          (Proj.C3 (cast AlonzoPrelude.d6) (cast AlonzoPrelude.d6)
                             (cast AlonzoPrelude.d6)
                             (cast AlonzoPrelude.d6)))
                       (cast AlonzoPrelude.d6))))
main = putStrLn d13
